### ISSUE TITLE
Discuss: Extend "Translate text in .po files" section

### ISSUE THREAD

**Issue by silopolis** [authoress/sphinx-intl-guide#3]
It would be nice that Transifex integration and setup be included in the guide.

Maybe another section presenting the workflow with an Open Source Desktop CAT tool would ice the cake as well as be a practical example of language dependent images with screenshots ?

**Comment by authoress** [comment]
You are right, it would be nice, but I have to learn how to do it first. I use Smartcat for translations ))

**Comment by silopolis** [comment]
Le jeu. 24 nov. 2022 à 18:16, Natalia ***@***.***> a écrit :

> You are right, it would be nice, but I have to learn how to do it first.
>
I'd gladly contribute that if you accept PRs :)

I use Smartcat for translations
>
Another one I have to have a look at now!

**Comment by authoress** [comment]
You are so kind )) Let me try it myself first, and you can catch the ball if I fail.

**Comment by authoress** [comment]
This is done.
https://github.com/authoress/sphinx-intl-guide/blob/main/docs/translate-text-in-po-files.rst

**Comment by silopolis** [comment]
Le mar. 10 janv. 2023 à 15:43, Natalia ***@***.***> a écrit :

> This is done.
>

Awesome! And best wishes for 2023 btw 🙂

Let me know when the Transifex (or other) project for the guide is setup.
I'm about to finish Nextcloud app translation and would love to follow up
with it...

TY
J

**Comment by authoress** [comment]
@silopolis best wishes to you to! The project in Transifex already exists, I just need to invite you somehow, I guess? (see the issue #4 )
