### ISSUE TITLE
Discuss: Add publishing section

### ISSUE THREAD

**Issue by silopolis** [authoress/sphinx-intl-guide#5]
Once our awesome project is cautiously documented, carefully translated and beautifully built, only thing left is for us to publish it.
This is a final step that's missing from the guide today that would close the circle.

Possible options that could be documented :

- Push/sync to any bare Web hosting
- GitHub pages
- And the all mighty ReadTheDocs.org !
  This last one of course already having docs (https://docs.readthedocs.io/en/latest/localization.html and https://docs.readthedocs.io/en/latest/guides/manage-translations-sphinx.html) may just be cross-referenced (who said intersphinx i18n ?)
  Note that they're already discussing to reference this guide into their docs in readthedocs/readthedocs.org#9000... Hope they'll join the tchat :)

Any other valuable option ?

**Comment by authoress** [comment]
No doubt Readthedocs would be a good option.

**Comment by authoress** [comment]
Ready, see #7
